version: "3.9"
services:

  redis:
    image: redis:alpine
    container_name: api-redis

  db:
    image: mysql:5.7
    container_name: api-mysql
    working_dir: /app
    volumes:
      - "db_data:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=apidb
      - MYSQL_USER=apidb
      - MYSQL_PASSWORD=password

  nginx:
    image: nginx:alpine
    container_name: api-nginx
    working_dir: /app
    volumes:
      - .:/app
      - ./docker/web/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"

  php:
    build: docker/php
    container_name: api-php
    working_dir: /app
    volumes:
      - .:/app
      #- ./src:/var/www/html
      #- ./docker/php/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini
#        - app_var:/application/var
#        - app_vendor:/application/vendor
#        - app_public_bundles:/application/public/bundles

volumes:
  db_data:
#  app_var:
#  app_vendor:

